### ISSUE TITLE
using latest tag neo4j

### ISSUE THREAD

**Issue by ghost** [joehoeller/nginx-server-neo4j-graph-db#1]
Hi,

When i am trying to use latest tag this wont work.

Do you know why ?

**Comment by daddydrac** [comment]
It was never meant for latest, only the versions of NEO4J that have a REST
API, which I believe is probably 3.3-3.9 or something like that.

**Comment by daddydrac** [comment]
you can switch the latest by changing the tag to whichever you prefer, i am closing this out now.
